appointments = [
    "Almoner",
    "Butler",
    "Chamberlain",
    "Chancellor",
    "Chapelmaster",
    "Chaplain",
    "Cofferer",
    "Confessor",
    "Constable",
    "Cup-bearer",
    "Dapifer",
    "Doorward",
    "Eunuch",
    "Falconer",
    "Gentleman of the Bedchamber",
    "Gentleman Usher",
    "Grand Almoner",
    "Grandmaster",
    "Grand Master of the Hunt",
    "Great officers",
    "Groom of the Stool",
    "Herald",
    "Intendant",
    "The Royal Fool",
    "Keeper of the Seal",
    "King of Arms",
    "Knight Marshal",
    "Earl Marshal",
    "Person-in-Waiting",
    "Person of Honour",
    "Majordomo",
    "Master of Ceremonies",
    "Master of the Horse",
    "Master of the Hunt",
    "Page",
    "Panter",
    "Grand Panetier",
    "Secretary",
    "Pursuivant",
    "Seneschal",
    "Stolnik",
    "Standard bearer",
    "Steward",
    "Usher"
]

chiefs = [
    "master",
    "administrator",
    "boss",
    "commander",
    "director",
    "guru",
    "instructor",
    "judge",
    "manager",
    "owner",
    "ruler",
    "teacher",
    "captain",
    "chief",
    "chieftain",
    "commandant",
    "controller",
    "general",
    "governor",
    "head",
    "overlord",
    "overseer",
    "preceptor",
    "principal",
    "superintendent",
    "supervisor",
    "president"
]

councils = [
    "Food Standards",
    "National Records",
    "Office of the Charity Regulator",
    "Registers",
    "Revenue",
    "Courts and Tribunals Service",
    "Fiscal Commission",
    "Housing Regulator",
    "Accounts Commission",
    "Architecture and Design",
    "Cairngorms National Park Authority",
    "Care Inspectorate",
    "Children's Hearings",
    "Community Justice",
    "Creative",
    "Crofting Commission",
    "Historic Environment",
    "Independent Living Fund",
    "The National Park Authority",
    "National Galleries",
    "National Library",
    "National Museums",
    "Enforcement Investigations and Review Commissioner",
    "Quality Meat",
    "Risk Management Authority",
    "Royal Botanical Garden",
    "Agricultural Wages Board",
    "Children's Reporter Administration",
    "Criminal Cases Review Commission",
    "Enterprise",
    "Environment Protection Agency",
    "Funding Council",
    "Futures Trust",
    "Land Commission",
    "Legal Aid Board",
    "Legal Complaints Commission",
    "Natural Heritage",
    "Qualifications Authority",
    "Social Services Council",
    "Skills Development",
    "Sports",
    "Water Industry Commission",
    "Judicial Appointments Board",
    "Local Government Boundary Commission",
    "Mobility and Access Committee",
    "Advisory Committee on Distinction Awards",
    "Commission on Social Security",
    "Law Commission",
    "Additional Support Needs Tribunals",
    "First-tier Tax Tribunal",
    "Lands Tribunal",
    "Mental Health Tribunal",
    "Parole Board",
    "Private Rented Housing Panel",
    "Charity Appeals Panel",
    "Upper Tax Tribunal",
    "Accountant in Bankruptcy",
    "Disclosure",
    "Education",
    "Forestry and Land",
    "Forestry",
    "Prison Service",
    "Public Pensions Agency",
    "Social Security",
    "Student Awards Agency",
    "Transport",
    "Commissioner for Ethical Standards in Public Life",
    "Commissioner For Children and Young People",
    "Human Rights Commission",
    "Information Commissioner",
    "Public Services Ombudsman",
    "Standards Commission",
    "Audit",
    "Convener of School Closure Review Panels",
    "Drinking Water Quality Regulator",
    "Inspector of Prisons",
    "Inspector of Prosecution",
    "Fire Service Inspectorate",
    "Inspector of Constabulary",
    "Justices of the Peace Advisory Committee",
    "Office of the Printer",
    "Fire and Rescue Service",
    "Guard Authority",
    "Road Works Commissioner"
]
