cognomens = [
    "the Able",
    "the Absolutist",
    "the Accursed",
    "the Adopted",
    "the Ætheling",
    "the Affable",
    "the African",
    "the Aggressor",
    "the All-fair",
    "the Allower",
    "the Ambitious",
    "the Ancient",
    "the Apostate",
    "the Apostle",
    "the Arab",
    "the Artist-King",
    "the Astrologer",
    "Augustus",
    "the Avenger",
    "the Bad",
    "the Bald",
    "Red Beard",
    "Barefoot",
    "Bareleg",
    "Barn-Lock",
    "the Bastard",
    "the Battler",
    "the Bavarian",
    "the Bear",
    "the Bearded",
    "Good Clerk",
    "Beer-Jug",
    "the Beloved",
    "the Bewitched",
    "the Big Nest",
    "the Black Prince",
    "the Black",
    "the Blessed",
    "the Blind",
    "the Blond",
    "Bloodaxe",
    "the Bloodthirsty",
    "the Bloody",
    "Bluetooth",
    "the Bold",
    "the Bolognian",
    "the Boneless",
    "the Bookish",
    "the Brash",
    "the Brave",
    "the Brilliant",
    "the Broad-shouldered",
    "Broom-plant",
    "the Brown",
    "the Bruce",
    "Builder",
    "the Builder King",
    "Bulgar-Slayer",
    "the Cabbage",
    "the Cardinal-King",
    "the Careless",
    "the Candid",
    "the Catholic",
    "the Caulker",
    "the Ceremonious",
    "the Chansonnier",
    "the Chaste",
    "the Chief",
    "the Child",
    "the Clubfoot",
    "Coal-Burner",
    "the Confessor",
    "the Conqueror",
    "the Constable Prince",
    "the Constant",
    "the Raven",
    "the Courteous",
    "the Crazy",
    "the Crosseyed",
    "Crouchback",
    "the Crowned",
    "the Cruel",
    "the Crusader",
    "the Curly",
    "Short Cloak",
    "the Damned",
    "the Accursed",
    "the Deacon",
    "the Debonaire",
    "the Deed-Doer",
    "the Desired",
    "the Determined",
    "the Devil",
    "the Diplomat",
    "Do-Nothing",
    "the Indolent",
    "the Sluggard",
    "the Devil",
    "the Drunkard",
    "the Dung-Named",
    "the Ecclesiastic",
    "the Priest",
    "the Edifier",
    "the Elbow-High",
    "the Ell-High",
    "the Elder",
    "the Eloquent",
    "the Emperor-Sacristan",
    "the Enlightened",
    "the Executioner",
    "the Exile",
    "the Fair",
    "Fairhair",
    "the Fair Sun",
    "the Farmer",
    "the Fat",
    "the Fearless",
    "the Fighter",
    "First-Crowned",
    "Fitzempress",
    "Flatnose",
    "Forkbeard",
    "the Fortunate",
    "the Fowler",
    "the Fratricide",
    "From Overseas",
    "the Generous",
    "the Liberal",
    "the Gentle",
    "the German",
    "the Glorious",
    "the God-Given",
    "the God-Like One",
    "the God-Loving",
    "the Good",
    "of Good Memory",
    "the Good Mother",
    "the Great",
    "Greyfell",
    "Greyhide",
    "Greymantle",
    "the Grim",
    "the Brave",
    "the Inexorable",
    "Gylle",
    "the Hairy",
    "the Hammer",
    "the Hammer of the Gods",
    "the Handsome",
    "the Hardy",
    "of Stern Counsel",
    "Harefoot",
    "the Holy",
    "the Holy Prince",
    "the Hopeful",
    "the Hunchback",
    "the Humane",
    "the Humanist",
    "Hunger",
    "the Hunter",
    "the Ill-Tempered",
    "the Illustrious",
    "the Impaler",
    "the Impotent",
    "the Inconstant",
    "the Fickle",
    "the Indolent",
    "the Independentist",
    "the Invincible",
    "the Iron",
    "Ironside",
    "the Just",
    "the Kind",
    "the Kind-Hearted",
    "Lackland",
    "the Lamb",
    "the Lame",
    "the Last",
    "Law-Mender",
    "the Lawgiver",
    "the Learned",
    "the Liberal",
    "the Liberator",
    "the Lion",
    "the Lionheart",
    "the Lisp",
    "the Lame",
    "the Little Impaler",
    "the Longhaired King",
    "Longshanks",
    "the Lover of Elegance",
    "the Mad",
    "the Madman",
    "the Magnanimous",
    "the Magnificent",
    "the Maiden",
    "the Hammer",
    "the Martyr",
    "the Memorable",
    "the Merry",
    "the Mild",
    "the Middle",
    "the Mighty",
    "Minus-a-Quarter",
    "Moneybags",
    "the Monk",
    "Monk's-Cloak",
    "the Loner",
    "the Moor",
    "the Beautiful",
    "the Navigator",
    "New-Day",
    "of the Nine Hostages",
    "the Noble",
    "No-Counsel",
    "the Unready",
    "the Oath-Taker",
    "the Old",
    "the One-Eyed",
    "the Oppressed",
    "the Orphan",
    "the Outlaw",
    "from Overseas",
    "the Pacific",
    "the Pale",
    "the Peaceful",
    "the Peacemaker",
    "the Perfect Prince",
    "the Philosopher",
    "the Philosopher King",
    "the Pious",
    "Ploughpenny",
    "the Popular",
    "the Populator",
    "the Posthumous",
    "the Powerful",
    "the Precious",
    "the Priest Hater",
    "the Proud",
    "the Prudent",
    "the Purple-Born",
    "the Quarreller",
    "the Quiet",
    "the Rash",
    "the Red",
    "the Red King",
    "the Redemptress",
    "the Redless",
    "the Redeless",
    "the Reformer",
    "the Restorer",
    "the Righteous",
    "Roundhead",
    "the Sacrificer",
    "the Sacristan",
    "the Sailor King",
    "the Saint",
    "the Saver of the Lands",
    "the Savior",
    "the Seer",
    "of the Nine Parts",
    "the Be-shitten",
    "the Short",
    "of Showers",
    "the Silent",
    "the Simple",
    "the Singer",
    "the Tax King",
    "the Sluggard",
    "the Soldier",
    "the Soldier-King",
    "the Sorcerer",
    "the Spider",
    "the Spirited",
    "Split-Nose",
    "the Stammerer",
    "the Stout",
    "the Strict",
    "the Strong",
    "the Sun King",
    "the Tall",
    "the Terrible",
    "the Theologian",
    "the Thunderbolt",
    "the Tough",
    "Transmarinus",
    "the Treacherous",
    "the Trembling",
    "the Tremulous",
    "of the Tributes",
    "the Troubadour",
    "the Tyrant",
    "the Unavoidable",
    "the Unique",
    "the Unlucky",
    "the Unready",
    "the Usurper",
    "the Vain",
    "the Valiant",
    "the Venetian",
    "the Victorious",
    "the Virgin",
    "the Warlike",
    "the Warrior",
    "the Weak",
    "Wearing-a-Cape",
    "the Well-Beloved",
    "the Well-Served",
    "the Wench of Queluz",
    "the White",
    "Who-Fights-Alone",
    "the Wicked",
    "the Wise",
    "the Wrymouth",
    "the Yellow",
    "the Blond",
    "the Young",
    "the Young King",
    "the Younger",
]
