mottos = [
    "Bless wells, O lord!",
    "By labour",
    "Act your office",
    "Whereby we cry, Abba, Father",
    "Always ready",
    "In thee, O Lord, have I put my trust",
    "Irritate not the lion",
    "Persevering and faithful",
    "By invincible truth",
    "Virtue is the only nobility",
    "Through",
    "Mercy is my desire",
    "He seeks high things",
    "In the cross is salvation",
    "Be silent",
    "Live that you may live",
    "Let fortune be attendant",
    "Faith undefiled",
    "Not too much",
    "Hence hope shines forth",
    "Wish nothing base",
    "Salvation through Christ",
    "He stands by his own powers",
    "Chosen for fidelity",
    "Boldly and honourably",
    "Victory is in truth",
    "The Lion of the Tribe of Judah lives",
    "I shall stand",
    "Through straits to heights",
    "While they watch",
    "Observe Observe",
    "Liberty",
    "Not in voice but a wish",
    "He conquers who endures",
    "Not to be shaken",
    "The acquirements of industry render illustrious",
    "Mindful of ancestral glory",
    "Valour advances the man",
    "I dare",
    "Loyal to death",
    "Loyal to the dead",
    "The cross is my pleasing rest",
    "A surer home in heaven",
    "Liberty and my native soil",
    "Truth under the cross",
    "To be rather than seem to be",
    "He conquers who endures",
    "Liberty under a pious king",
    "It much becomes us to live honourably",
    "Let the deed shaw",
    "I revive from my burial",
    "Stand sure",
    "That is valuable which is useful",
    "Let us be viewed by our actions",
    "The beaten road is a safe road",
    "God keep me",
    "Be faithful",
    "By counsel, not by force",
    "After clouds sunshine",
    "In the cross is salvation",
    "An oak in aged strength",
    "We are born from the broken oak",
    "Virtue under strength",
    "We have been",
    "Think and thank",
    "Consider the end",
    "Piety is the surest virtue",
    "Vigilance",
    "Stand sure",
    "To the end",
    "Under this sign thou shalt conquer",
    "Plucked they will emit fragrance",
    "Even when plucked they will give out scent",
    "Things sprung form virtue rarely perish",
    "And live in hope",
    "I live in hope",
    "Honour and virtue",
    "Prepared in either case",
    "Victory is in truth",
    "Yield not to misfortunes",
    "I trample it under my feet",
    "Nothing resists valour and arms",
    "May the Alder always flourish",
    "Direct us",
    "I neither despise nor fear",
    "He is led, not drawn",
    "I keep faith",
    "By sea and land",
    "Without virtue viler than the sea-weed",
    "Truth conquers",
    "Another is not wanting",
    "He bravely supports the cross",
    "I follow the highest tracks of things",
    "By valour and exertion",
    "I trust in the cross",
    "In defence",
    "In defence of the distressed",
    "My defence",
    "He lives well who lives peacefully",
    "Once and always",
    "Watch",
    "Friendship without deceit",
    "Diligently and faithfully",
    "May God direct us",
    "By faith and labour",
    "In God alone I have trust",
    "Remember",
    "I triumph equally in death as in life",
    "Triumph in life or death",
    "Let not thy own, but the public wishes actuate thee",
    "God is every thing",
    "To God alone",
    "Mack all sicker",
    "Remember the death of Alpin",
    "Royal is the reward of virtue",
    "Immoveable",
    "Toward heaven",
    "By patience thou wilt conquer",
    "By the favour of God",
    "I will hope",
    "Sweet in the memory",
    "Yield not to misfortunes",
    "By constancy and virtue",
    "Victory increases by concord",
    "Dare to be wise",
    "He conquers who endures",
    "Hold fast",
    "Boldly and rightly",
    "Skilfully",
    "By degrees",
    "Nothing to be despaired of under the auspices of God",
    "By sea",
    "He who acts honestly acts bravely",
    "That is rightly which is honestly done",
    "Stand sure",
    "We stoop not",
    "By valour and good fortune",
    "Give and forgive",
    "Wisdom the conqueror of fortune",
    "The love of the cross gives strength",
    "By its opposite",
    "A snake in the grass",
    "The snake lurks in the grass",
    "Truth is strong",
    "Go to the ant",
    "God send me wel to kepe",
    "I will hope",
    "I hope",
    "For me and for mine",
    "Better things remain",
    "Through love to virtue",
    "Never despair",
    "I had perished, unless I had gone through with it",
    "Always ready",
    "I hope for better things",
    "Mindful of God, grateful to friends",
    "Strive that you may live for ever",
    "When the young, ones of the crows call upon him",
    "Innocent and true",
    "Harmlessly and providently",
    "Inward things are best",
    "Praise be to God",
    "As well internal as external",
    "Praise be to God",
    "That I may be replenished",
    "Tried fidelity enriches",
    "The palm is not obtained without labour",
    "Following my destiny",
    "Those things only are good which are honest",
    "God the only salvation",
    "Ready",
    "That I may be replenished",
    "Nothing shall oppose him as he goes",
    "By patience thou wilt conquer",
    "Under the white cross",
    "I am brave and confident",
    "I scarce call these things our own",
    "Virtue is stronger than a battering-ram",
    "While I have breath I hope",
    "He lives well who lives industriously",
    "I have endured and done much",
    "Follow reason",
    "Boldly and faithfully",
    "Virtue is the safest helmet",
    "Unconquered by labour",
    "I remain unconquered",
    "By force and arms",
    "Without time",
    "Hoped for and fulfilled",
    "Constant and faithful",
    "Watch that you may live",
    "Now or never",
    "Hoped for and fulfilled",
    "Under this sign thou shalt conquer",
    "Peace is acquired by arms",
    "I claim ancient honour",
    "Thrust aside obstacles",
    "From the swallow",
    "Give unto God",
    "A prey to no one",
    "To God, my country, and my friends",
    "To serve God is to reign",
    "Vigilance, strength, pleasure",
    "While I have breath I hope",
    "Regardless of his own interest",
    "A mind conscious of rectitude",
    "Whatever grows perishes in ashes",
    "The king and the state",
    "Will God and I shall",
    "Courage in difficulties",
    "Be just, and fear not",
    "Fight",
    "Not for ourselves, but for all mankind",
    "I trust in the Lord",
    "Read and learn",
    "All things are from one",
    "Ashmore Cave! Adsum Beware! I am present",
    "To act for others",
    "Fortune is the companion of valour",
    "To a degenerate man his family is a disgrace",
    "He conquers who endures",
    "Do and hope",
    "Patience masters all chances",
    "Virtue is the strongest shield",
    "While I have breath I hope",
    "I neither arrogate nor hesitate",
    "Trust, but in whom take care",
    "I glorify under the cross",
    "Trust, but in whom take care",
    "Persevering in justice",
    "Our wealth is dug out of the earth",
    "I stand by God and my country",
    "Ready",
    "Ready to accomplish",
    "In hope of the latter time",
    "Observe Observe",
    "While they watch",
    "I would rather die than be disgraced",
    "Furth fortune, and fill the fetters Furth fortune, and fill the fetters",
    "Be just, and fear not",
    "By the sword",
    "Cautiously and carefully",
    "Trust in God",
    "Believe in God",
    "Faithful to God and the king",
    "It is the part of a pious man to love God and his country",
    "Nothing without labour",
    "By the providence of God",
    "He conquers arms by laws",
    "Loyal to the dead",
    "I will honour those who honour me",
    "From a high hill",
    "To conquer is to live enough",
    "Let us go where fortune leads",
    "Help, O God!",
    "With faith and fortitude",
    "Be faithful",
    "I bear the sun",
    "Where there is love there is faith",
    "While I have breath I hope",
    "If there be prudence",
    "I hold it",
    "Thank you, fortune",
    "Be what you seem to be",
    "Virtue is preferable to splendour",
    "By valour and constancy",
    "Another is not wanting",
    "I know in whom I trust",
    "Not too much of anything",
    "The cross is our crown",
    "When one is torn away another is not wanting",
    "God prospers the just",
    "To have and to share with others",
    "I will remember it",
    "They will rise again",
    "To live without a wish concealed",
    "Not in vain Not in vain",
    "Hallelujah",
    "Steady",
    "True and faithful ever",
    "During life",
    "Courage without fear",
    "They flourish in glad air",
    "Lighter than air",
    "By virtue and vows",
    "Do and hope",
    "No Foe May Pass",
    "Never Resting",
    "As High as Honor",
    "Our Sun Shines Bright",
    "Beware Our Sting",
    "Our Blades are Sharp",
    "Pride and Purpose",
    "Death Before Disgrace",
    "No Song So Sweet",
    "Honed and Ready",
    "Though All Men Do Despise Us",
    "None so Fierce",
    "By Day or Night",
    "The Wind Our Steed",
    "Ever Vigilant",
    "None so Wise",
    "Tread Lightly Here",
    "Iron From Ice (Telltale Game)",
    "A Taste of Glory",
    "Let Me Soar",
    "Work Her Will",
    "Rouse Me Not",
    "None So Dutiful",
    "We Light the Way",
    "Righteous in Wrath",
    "Let It be Written",
    "The Sun of Winter",
    "The Choice is Yours",
    "Burning Bright",
    "Here We Stand",
    "Above the Rest",
    "Behold Our Bounty",
    "Wisdom and Strength",
    "Our Roots Go Deep",
    "Unflinching",
    "Set Down Our Deeds",
    "Brave and Beautiful",
    "Come Try Me",
    "As Strong as Stone",
    "We Remember",
    "True to the Mark",
    "Family is Hope, Protect it Always",
    "I Have No Rival",
    "From These Beginnings",
    "Proud to Be Faithful",
    "Truth Conquers",
    "Awake! Awake!",
    "Proud and Free",
    "First in Battle",
    "When All is Darkest",
    "Fly High, Fly Far",
    "So End Our Foes",
    "Family, Duty, Honor",
    "Growing Strong",
    "The Old, the True, the Brave",
    "Light in Darkness",
    "For All Seasons",
    "Sound the Charge",
    "Honor, not Honors",
    "Death Over Dishonor",
    "Ever Higher",
    "Touch Me Not",
    "Right Conquers Might",
    "We Guard the Way",
    "He seeks high deeds",
    "Salvation through Christ",
    "Loyal unto death",
    "The cross gives me welcome rest",
    "For country often, for King always",
    "I would have perished had I not persisted",
    "Praise God",
    "I remain unvanquished",
    "By fidelity and labour",
    "What is brighter than the stars?",
    "The Lord has done this",
    "Neither fast nor slow",
    "For my county",
    "Either to do or die",
    "Gracious",
    "He who leads",
    "I trust",
    "The Lord will provide",
    "We have been",
    "Not having followed mean pursuits",
    "Hence the brighter honour",
    "Unite",
    "Do not forget",
    "Do and Hope",
    "Always ready",
    "I am fierce with the fierce",
    "He rouses us with song",
    "If i can",
    "I cannot forget",
    "I have Good Hope",
    "Live for God and you shall have life",
    "I will give you safety though strength",
    "What would one not do for his country",
    "Glory is the reward of valour",
    "Never behind",
    "Honour crowns virtue",
    "Try",
    "I trust",
    "Virtue Increases Honor",
    "Boldly and rightly",
    "I think more",
    "By fidelity and fortitude",
    "Sweeter after difficulties",
    "A repairer of ruin",
    "I am ready",
    "Gentler because of the obstruction",
    "It sustains, it enriches, it pleases",
    "The rock of alarm",
    "My race is royal",
    "More secure by this",
    "Either peace or war",
    "I stand for the truth",
    "The Lord has given",
    "But hope is unbroken",
    "I accomplish the hunt",
    "Flourishing both in sunshine and in shade",
    "Never unprepared",
    "Truth conquers",
    "Wandering lights deceive",
    "I grow by virtue",
    "I open locked hearts",
    "This is valour of my ancestors",
    "In Thee O Lord have I put my trust",
    "Sweet danger",
    "The rock of the raven",
    "To conquer or die",
    "To conquer or die",
    "God assists",
    "By the grace of God and king",
    "Through difficulties",
    "I will never forget",
    "With a strong hand",
    "I shine not burn",
    "Endeavour",
    "Fortune assists the daring",
    "Brave and faithful",
    "To conquer or die",
    "The boar's rock",
    "Hill of Fire",
    "While i breathe i hope",
    "I learn to succour the unfortunate",
    "Let fear be far from all",
    "To conquer or die",
    "With fortitude",
    "Not forgetful",
    "I will overcome envy with God's help",
    "By wisdom and courage",
    "Thinks more",
    "Long live the king",
    "Heaven at last",
    "Brave in difficulty",
    "I hope for better things",
    "Watch well",
    "An interest after death",
    "Provide for all",
    "Boldly and readily",
    "Boldly and strongly",
    "By faith and trust",
    "By faith and confidence",
    "Pray and labour",
    "My wishes are above the stars",
    "Fortune passes over everywhere",
    "Disperse",
    "By faith and fortitude",
    "A palace the reward of bravery",
    "If God is for us, who is against us",
    "Courage grows strong at a wound",
    "I do not fear but am careful",
    "The lion's anger is noble",
    "I hope",
    "In readiness",
    "For liberty",
    "Not degenerate",
    "Not unworthy",
    "Nothing truer than truth",
    "I think",
    "Safe on the waves"
]
