races = [
    "Aarakocra",
    "Aasimar (Fallen)",
    "Aasimar (Protector)",
    "Aasimar (Scourge)",
    "Bugbear",
    "Centaur",
    "Changeling",
    "Dragonborn",
    "Dwarf (Duergar)",
    "Dwarf (Hill)",
    "Dwarf (Mark of Warding)",
    "Dwarf (Mountain)",
    "Elf (Drow)",
    "Elf (Eladrin)",
    "Elf (High)",
    "Elf (Mark of Shadow)",
    "Elf (Sea)",
    "Elf (Shadar-kai)",
    "Elf (Wood)",
    "Firbolg",
    "Genasi (Air)",
    "Genasi (Earth)",
    "Genasi (Fire)",
    "Genasi (Water)",
    "Gith (Githyanki)",
    "Gith (Githzerai)",
    "Gnome (Deep)",
    "Gnome (Deep/Svirfneblin)",
    "Gnome (Forest)",
    "Gnome (Mark of Scribing)",
    "Gnome (Rock)",
    "Goblin",
    "Goliath",
    "Half-Elf (Aquatic Elf Descent)",
    "Half-Elf (Base)",
    "Half-Elf (Drow Descent)",
    "Half-Elf (Mark of Detection)",
    "Half-Elf (Mark of Storm)",
    "Half-Elf (Moon Elf or Sun Elf Descent)",
    "Half-Elf (Wood Elf Descent)",
    "Half-Orc",
    "Half-Orc (Mark of Finding)",
    "Halfling (Ghostwise)",
    "Halfling (Lightfoot)",
    "Halfling (Mark of Healing)",
    "Halfling (Mark of Hospitality)",
    "Halfling (Stout)",
    "Hobgoblin",
    "Human (Mark of Finding)",
    "Human (Mark of Handling)",
    "Human (Mark of Making)",
    "Human (Mark of Passage)",
    "Human (Mark of Sentinel)",
    "Kalashtar",
    "Kenku",
    "Kobold",
    "Lizardfolk",
    "Loxodon",
    "Minotaur",
    "Orc",
    "Shifter (Beasthide)",
    "Shifter (Longtooth)",
    "Shifter (Swiftstride)",
    "Shifter (Wildhunt)",
    "Simic Hybrid",
    "Tabaxi",
    "Tiefling (Asmodeus)",
    "Tiefling (Baalzebul)",
    "Tiefling (Base)",
    "Tiefling (Dispater)",
    "Tiefling (Fierna)",
    "Tiefling (Glasya)",
    "Tiefling (Levistus)",
    "Tiefling (Mammon)",
    "Tiefling (Mephistopheles)",
    "Tiefling (Variant)",
    "Tiefling (Zariel)",
    "Triton",
    "Vedalken",
    "Verdan",
    "Warforged",
    "Yuan-ti Pureblood"
]
